loginapp/urls.py
from django.urls import path
from loginapp import views

# app别名：
app_name='loginapp'

# 路由系统
urlpatterns = [
    # 登录视图函数路径
    path('login_view/',views.login_view,name='login_view'),
#     注册视图路径
    path('register_view/',views.register_view,name='register_view'),
#     注册成功视图路径
    path('register_ok_view/',views.register_ok_view,name='register_ok_view'),
#     验证码路由
    path('create_img_code/',views.create_img_code,name='create_img_code'),
#     ajax判断email路由
    path('decide_email_name/',views.decide_email_name,name='decide_email_name'),
#     ajax判断验证码路由
    path('decide_img_code/',views.decide_img_code,name='decide_img_code'),
#     判断注册是否成功路由
    path('decide_register_is_success/',views.decide_register_is_success,name='decide_register_is_success'),
#     登录注册成功跳转判断
    path('register_login_success_jump/',views.register_login_success_jump,name='register_login_success_jump'),
#     登录判断路由
    path('decide_login_is_success/',views.decide_login_is_success,name='decide_login_is_success'),
#     登出状态路由
    path('login_status_exit/',views.login_status_exit,name='login_status_exit'),
#     设置账号激活码路由
    path("set_ID_active/",views.set_ID_active,name="set_ID_active"),
#     发送激活验证
    path('send_active/',views.send_active,name="send_active"),
    # 激活页面
    path("set_active_riew/",views.set_active_riew,name="set_active_riew"),
]

mainapp/urls.py
from django.urls import path
from mainapp import views

# app别名
app_name='mainapp'

# 路由
urlpatterns = [
    # 主页面路由
    path('index/',views.index_view,name='index'),
    # 图书详情页路由
    path('bookDetail/',views.book_detail_view,name='bookDetail'),
    # 图书分类路由
    path('booklist/',views.book_list_view,name='booklist'),
]

middle_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('main/',include('mainapp.urls')),
    path('login/',include('loginapp.urls')),
    path('car/',include('shopping_car_app.urls')),
]

shopping_car_app/urls.py
from django.urls import path
from shopping_car_app import views

# 购物车app别名：
app_name='shopping_car_app'

# 购物车路由系统
urlpatterns = [
#     购物车视图函数路由
    path('shopping_car_view/',views.shopping_car_view,name="shopping_car_view"),
#     地址页面视图路由
    path("shopping_car_indent_view/",views.shopping_car_indent_view,name="shopping_car_indent_view"),
# 购物车订单完成视图路由
    path("shopping_car_indent_ok_view/",views.shopping_car_indent_ok_view,name="shopping_car_indent_ok_view"),
#     添加书减少数到购物车函数路由
    path("add_book_into_car/",views.add_book_into_car,name="add_book_into_car"),
#     改变书数量到购物车路由
    path('change_book_into_car/',views.change_book_into_car,name='change_book_into_car'),
#     删除书路由
    path('delete_book/',views.delete_book,name='delete_book'),
#     恢复书
    path("find_book/",views.find_book,name="find_book"),
#     顾客确定路由
    path("customer_sure_view/",views.customer_sure_view,name='customer_sure_view'),
#     订单提交提交判断路由
    path("user_indent_dispose/",views.user_indent_dispose,name="user_indent_dispose"),

]

shopping_car_app/models.py
from django.db import models

# Create your models here.

shopping_car_app/views.py
import time
from django.db import transaction
from django.http import HttpResponse
from django.shortcuts import render,redirect
from tools.shopping_car import Car
# Create your views here.


from mainapp.models import TBooks, TAdress, TOrder, TOrderiterm, TUser

# 购物车视图函数
'''
说明：
1、session中存：shop_car_obj，是购物车对象
2、session中存：session_user_obj，是用户对象
'''
# 购物车视图
def shopping_car_view(request):
    # 保存session用于判断用户在哪个页面
    request.session['user_session_status'] = 2
    # 获得登录状态
    userobj=request.session.get('session_user_obj')
    # 获得商品信息
    shop_car_obj=request.session.get("shop_car_obj")
    return render(request,'shopping_car_app/car.html',{
    #     传登录状态
        'userobj':userobj,
    #     传入购物车书籍列表对象
        'shop_car_obj':shop_car_obj,
    })

# 地址页面视图
def shopping_car_indent_view(request):
    # 获得购物车对象，存在session中
    shop_car_obj = request.session.get('shop_car_obj')
    if shop_car_obj:
        # 获得登录状态
        userobj=request.session.get('session_user_obj')
        # 获得用户地址
        user_address_obj=TAdress.objects.filter(user=userobj.id)
        return render(request,'shopping_car_app/indent.html',{
        #     传登录状态
            'userobj':userobj,
        #     传入购物车信息
            "shop_car_obj":shop_car_obj,
        #     传入用户地址
            "user_address_obj":user_address_obj,
        })
    else:
        return redirect(to="shopping_car_app:shopping_car_view")

# 购物车订单完成视图
def shopping_car_indent_ok_view(request):
    # 保存session用于判断用户在哪个页面
    request.session['user_session_status'] = 2
    # 获得登录状态
    userobj=request.session.get('session_user_obj')
    # 获得订单id
    indent_num=request.GET.get('indent_num')
    # 获得订单id对象
    indent_num_obj=TOrder.objects.filter(id=indent_num)
    if indent_num_obj:
        indent_num_obj=indent_num_obj[0]
    return render(request,'shopping_car_app/indent ok.html',{
    #     传登录状态
        'userobj':userobj,
    #     传订单对象
        "indent_num_obj":indent_num_obj,
    })

# ajax添加购物车,增加减少书籍数量函数
def add_book_into_car(request):
    # 从前端获得数据：书的id和书的数量
    bookId=request.POST.get("bookId")
    bookCount=request.POST.get("bookCount")
    if not bookCount:
        bookCount=1
    # 判断否能重前端获得添加书的数据
    if bookId and bookCount:
        # 判断数据库中是否有这本书
        book_obj=TBooks.objects.filter(id=bookId)
        # 如果有这本书，添加进购物车
        if book_obj:
            # 判断购物车对象是否存在session中
            shop_car_obj=request.session.get('shop_car_obj')
            # 添加事务控制，出错回滚
            with transaction.atomic():
                # 如果购物车存在session中
                if shop_car_obj:
                    # 调Car对象的添加书的方法
                    shop_car_obj.add_book(bookId,bookCount)
                else:
                #     如果不存在，创建对象并调用的添加书的方法
                    shop_car_obj=Car()
                    # 调Car对象的添加书的方法
                    shop_car_obj.add_book(bookId, bookCount)
                #     shop_car_obj保存到session中
                request.session["shop_car_obj"]=shop_car_obj
                return HttpResponse('添加成功')
        else:
            HttpResponse('添加失败')
    else:
        return HttpResponse('添加失败')

# ajax改变书数量
def change_book_into_car(request):
    # 从前端获得数据：书的id和书的数量
    bookId=request.POST.get("bookId")
    bookCount=request.POST.get("bookCount")
    # 获得购物车对象，存在session中
    shop_car_obj = request.session.get('shop_car_obj')
    # 添加事务控制，出错回滚
    with transaction.atomic():
        # 如果购物车存在session中
        if shop_car_obj:
            # 添加事务控制，出错回滚
            shop_car_obj.book_change(bookId, bookCount)
            #     shop_car_obj保存到session中
            request.session["shop_car_obj"] = shop_car_obj
            return HttpResponse('成功')
        else:
            return HttpResponse('失败')

# 删除书
def delete_book(request):
    bookId = request.POST.get("bookId")
    # 获得购物车对象，存在session中
    shop_car_obj = request.session.get('shop_car_obj')
    # 添加事务控制，出错回滚
    with transaction.atomic():
        # 如果购物车存在session中
        if shop_car_obj:
            # 添加事务控制，出错回滚
            shop_car_obj.delete_book(bookId)
            #     shop_car_obj保存到session中
            request.session["shop_car_obj"] = shop_car_obj
            return HttpResponse('成功')
        else:
            return HttpResponse('失败')

# 恢复书
def find_book(request):
    bookId = request.POST.get("bookId")
    # print(type(bookId),bookId)
    # 获得购物车对象，存在session中
    shop_car_obj = request.session.get('shop_car_obj')
    # 添加事务控制，出错回滚
    with transaction.atomic():
        # 如果购物车存在session中
        if shop_car_obj:
            # 添加事务控制，出错回滚
            shop_car_obj.recover_car_book(bookId)
            #     shop_car_obj保存到session中
            request.session["shop_car_obj"] = shop_car_obj
    return redirect(to="shopping_car_app:shopping_car_view")

# 订单确定页面视图函数
def customer_sure_view(request):
    # 获得登录状态
    userobj=request.session.get('session_user_obj')
    # 获得购物车对象，存在session中
    shop_car_obj = request.session.get('shop_car_obj')
    # 判断购物车对象存在不，不存在跳转购物车视图
    if shop_car_obj:
        return render(request,'shopping_car_app/customer_sure.html',{
        #     传入购物车信息
            "shop_car_obj":shop_car_obj,
        #     传登录状态
            'userobj':userobj,
        })
    else:
        return redirect(to="shopping_car_app:shopping_car_view")

# 用户订单提交处理函数
def user_indent_dispose(request):
    # 获得购物车对象
    # 获得购物车对象，存在session中
    shop_car_obj = request.session.get('shop_car_obj')
    # 获得收货人姓名
    consignee_name=request.POST.get('ship_man_name')
    # 获得收件人国家
    consignee_country = request.POST.get('country_id')
    # 获得收货地址
    consignee_address=request.POST.get('province_id')
    # 获得收货人详细地址
    consignee_small_address=request.POST.get('ship_man_address')
    # 获得收货人邮编
    consignee_code=request.POST.get('ship_man_code')
    # 获得收货人手机
    consignee_tel_phone=request.POST.get('ship_man_tel_phone')
    # 获得收货人座机
    consignee_phone_number=request.POST.get('ship_man_phone_number')
    # 是否为新地址
    is_new_address=request.POST.get('address_choose')
    # 获得用户对象
    # 获得登录状态
    userobj=request.session.get('session_user_obj')

    # 检查是否为空,为空返回订单视图
    if consignee_name and consignee_country and consignee_address and consignee_small_address and consignee_code and (consignee_tel_phone or consignee_phone_number):
        # 判断是否在登录状态
        # 在则添加，不在则返回登录
        if userobj:
            # 查出登录用户对应id
            user_id_obj = TUser.objects.get(id=userobj.id)
            # 预防添加出错
            try:
            #     事务控制
                with transaction.atomic():
                    # # 地址拼接
                    # result_address="%s+%s+%s"%(consignee_country,consignee_address,consignee_small_address)
                    # 如果不是新地址添加新地址
                    if is_new_address == 'no_val':
                        address_obj =TAdress.objects.create(user =user_id_obj,
                                               name =consignee_name,
                                               detail_address =consignee_country,
                                               detail_address1 =consignee_address,
                                               detail_address2 =consignee_small_address,
                                               zipcode =consignee_code,
                                               telphone=consignee_tel_phone,
                                               addr_mobile=consignee_phone_number,)
            #
                    else:
                        # 如果存在则根据获得的id查找对应的地址
                        address_obj=TAdress.objects.get(id=is_new_address)
            #         创建订单号:12位的当前时间
                    indent_num=int(time.time()*1000)
            #         创建订单表
                    book_order_obj=TOrder.objects.create(user =user_id_obj,
                                          adress =address_obj,
                                          num =indent_num,
                                          create_date =time.strftime("%H:%M:%S", time.localtime()),
                                          price =shop_car_obj.total_price,
                                          status =1)
            #     创建订单项表
            #
                    for i in shop_car_obj.book_list:
                        # 获得书籍对象
                        book_obj=TBooks.objects.get(id=i.book.id)
                        # 改变书籍销量
                        book_obj.sales+=i.bookCount
                        book_obj.save()
                        TOrderiterm.objects.create(order =book_order_obj,
                                                   book =book_obj,
                                                   shop_num =i.bookCount,
                                                   total_price =i.bookCount*i.book.book_dprice)
            #         删除session中购物车对象
                    del request.session["shop_car_obj"]
            except BaseException as errors:
                print(errors)
            #     错误返回订单视图
                return redirect(to='shopping_car_app:shopping_car_indent_view')
            #     成功返回订单提交成功视图,传订单号
            else:
                return redirect("/car/shopping_car_indent_ok_view/?indent_num="+str(book_order_obj.id))
        else:
            return redirect(to='loginapp:login_view')
    else:
        return redirect(to='shopping_car_app:shopping_car_indent_view')

shopping_car_app/templates/shopping_car_app/customer_sure.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
{% load static %}
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<link href="/static/css/bootstrap.css" rel="stylesheet" type="text/css" />
<title>顾客确定</title>
<script src="/static/js/jquery_1.8.js"></script>
    <script src="/static/js/jquery_cookie.js"></script>
	<link rel="shortcut icon" href="/static/images/favicon.ico?v=20160901" type="image/x-icon">
    <link href="/static/css/shopping_cart_new.css" rel="stylesheet" type="text/css">
	<link href="/static/css/bootstrap.min.css" type="text/css" />

    <style type="text/css">
        li{

        }
    </style>
</head>
<form action="http://search.dangdang.com/search.aspx" id="bootpagetopSearch" name="bootpagetopSearch" method="GET"></form>
<script type="text/javascript">var nick_num = 0;initHeaderOperate();</script><script type="text/javascript" src="http://orderb.dangdang.com/queryunpaid?callback=Unpaid_Data"></script>
		<div class="shoppingcart_wrapper" id="ad_cpt_11850"><div><a href="http://a.dangdang.com/tjump.php?q=ddo84XQOf357bOs8tXGg5%2F%2F0oVoDImt3DFWsMqu7ZMSVsfUMeOQJueASNiMLjq%2FdrXMLCKnVfyKEahteAh1ih%2ByKYrKGzhvL20LVbDzObRambBA0YPpivy5hR5foQ4Rt%2BTB" target="_blank" rel="nofollow"><img src="http://img62.ddimg.cn/2017/1/11/2017011111344969879.jpg"></a></div></div>
<div class="logo_line">
    <div class="w960">
        <div class="shopping_procedure"><span class="current">我的购物车</span><span>填写订单</span><span>完成订单</span></div>
        <div class="logo"><a href="#"><img src="/static/images/bz_logo_car.jpg" alt=""></a></div>
    </div>
</div>
<body style="padding-bottom:82px">

<link href="/static/css/header_960_150611.css" rel="stylesheet" type="text/css">
<script src="/static/js/pagetop2015_0827.js" charset="gb2312" type="text/javascript"></script>

<div id="hd">
<div id="tools">
<div class="tools">
    <div class="ddnewhead_operate" dd_name="顶链接">
        
        <div class="ddnewhead_welcome" display="none;">
            <span id="nickname"><span class="hi">Hi，<a href="http://myhome.dangdang.com/" class="login_link" target="_blank"><b>159**…</b></a><a href="javascript:PageTopSignOut();" target="_self">[退出]</a></span></span>
            <div class="tel_pop" style="display:none" id="__ddnav_sjdd" onmouseover="showgaoji('a_phonechannel','__ddnav_sjdd');" onmouseout="hideotherchannel('a_phonechannel','__ddnav_sjdd');">
                <a target="_blank" href="http://t.dangdang.com/20130220_ydmr" class="title"><i class="icon_tel"></i>手机当当</a><i class="title_shadow"></i>
                <ul class="tel_pop_box">
                    <td><a href="http://t.dangdang.com/20130220_ydmr" dd_name="手机二维码"><span>当当手机客户端</span><img src="http://img3.ddimg.cn/00363/doc/erweima2.png"><span class="text">随手查订单<br>随时享优惠</span></a></td>
                </ul>
            </div>
        </div>
        <div class="new_head_znx" id="znx_content" style="display:none;"></div>
    </div>
</div>
</div>
<div id="header_end"></div>
{#内容#}
<div>
    <div class="table-responsive" style="margin-left: 100px; margin-top: 100px; margin-right: 100px">
        <h1 class="h2">订单确定表</h1>
      <table class="table table-striped h3" >
            <tr>
                <td>封面</td>
                <td>名字</td>
                 <td>出版社</td>
                <td>百知价</td>
                <td>市场价</td>
                <td>数量</td>
                <td>小计</td>

            </tr>
          {% for i in shop_car_obj.book_list %}
            <tr>
               <td><img src="/static/{{ i.book.product_image_path }}" alt=""/></td>
                <td>{{ i.book.book_name }}</td>
                <td>{{ i.book.book_publish }}</td>
                <td>￥{{ i.book.book_dprice }}</td>
                <td>￥{{ i.book.book_price }}</td>
                <td>{{ i.bookCount }}</td>
                <td>{% widthratio i.bookCount 1 i.book.book_dprice %}</td>

            </tr>
          {% endfor %}
      </table>
    <div style="margin-top: 30px; margin-left:800px">
        <h3 class="h3" style="color: red">节省价￥{{ shop_car_obj.save_price }}</h3>
        <h3 class="h3" style="color: red">总价￥{{ shop_car_obj.total_price }}</h3>
        <a href="{% url 'shopping_car_app:shopping_car_indent_view' %}"><input class="btn" type="button" value="确定"/></a>
        <a href="{% url 'shopping_car_app:shopping_car_view' %}"><input class="btn" type="button" value="返回"/></a>
    </div>
    </div>



</div>



<div id="footer">
<div class="footer">
	<div class="footer_nav_box">
		<div class="footer_copyright"><span>Copyright (C) 当当网 2004-2014, All Rights Reserved</span><a href="http://www.hd315.gov.cn/beian/view.asp?bianhao=010202001051000098" target="_blank" class="footer_img" rel="nofollow"><img src="http://img4.dangdang.com/bottom/validate.gif"></a><span><a href="http://www.miibeian.gov.cn/" target="_blank" rel="nofollow">京ICP证041189号</a></span><span>出版物经营许可证&nbsp;新出发京批字第直0673号</span></div>
	</div>
</div>
</div>
    <div class="foot_tip_ad">广告</div>
    <style>
        .foot_tip_ad { width:40px; height:40px; font:12px/40px "simsun"; text-align:center; color:#fff; background-color:#474747; position:fixed; right:0; bottom:10px;_position:absolute; _bottom:auto;_top:expression(eval(document.documentElement.scrollTop+document.documentElement.clientHeight-this.offsetHeight-(parseInt(this.currentStyle.marginTop,10)||0)-(parseInt(this.currentStyle.marginBottom,10)||0)));}
    </style>


</body>
</html>

shopping_car_app/templates/shopping_car_app/indent ok.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
{% load static %}
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>OK</title>
<script src="/static/js/jquery_1.8.js"></script>
    <script src="/static/js/jquery_cookie.js"></script>
	<link rel="shortcut icon" href="/static/images/favicon.ico?v=20160901" type="image/x-icon">
    <link href="/static/css/shopping_cart_new.css" rel="stylesheet" type="text/css">
	<link href="/static/css/footer_150526.css" rel="stylesheet" type="text/css" />
</head>

<body style="padding-bottom:82px">

<link href="/static/css/header_960_150611.css" rel="stylesheet" type="text/css">
<script src="/static/js/pagetop2015_0827.js" charset="gb2312" type="text/javascript"></script>

<div id="hd">
<div id="tools">
<div class="tools">
    <div class="ddnewhead_operate" dd_name="顶链接">
        
        <div class="ddnewhead_welcome" display="none;">
{#   判断是否登录#}
            {% if userobj %}
                <span id="nickname_login">
                欢迎登陆：{{ userobj.user_name }}|
                <a href="{% url 'loginapp:login_status_exit' %}">登出</a>
                </span>
            {% else %}
                <span id="nickname">
                    <span class="hi hi_none">欢迎光临当当，请</span>
                    <a href="{% url 'loginapp:login_view' %}?status=2" class="login_link">登录</a><a href="{% url 'loginapp:register_view' %}?status=2">免费注册</a>
                </span>
            {% endif %}            <div class="tel_pop" style="display:none" id="__ddnav_sjdd" onmouseover="showgaoji('a_phonechannel','__ddnav_sjdd');" onmouseout="hideotherchannel('a_phonechannel','__ddnav_sjdd');">
                <a target="_blank" href="http://t.dangdang.com/20130220_ydmr" class="title"><i class="icon_tel"></i>手机当当</a><i class="title_shadow"></i>
                <ul class="tel_pop_box">
                    <li><a href="http://t.dangdang.com/20130220_ydmr" dd_name="手机二维码"><span>当当手机客户端</span><img src="http://img3.ddimg.cn/00363/doc/erweima2.png"><span class="text">随手查订单<br>随时享优惠</span></a></li>
                </ul>
            </div>
        </div>
        <div class="new_head_znx" id="znx_content" style="display:none;"></div>
    </div>
</div>
</div>
<div id="header_end"></div>
</div>
<form action="http://search.dangdang.com/search.aspx" id="bootpagetopSearch" name="bootpagetopSearch" method="GET"></form>
<script type="text/javascript">var nick_num = 0;initHeaderOperate();</script><script type="text/javascript" src="http://orderb.dangdang.com/queryunpaid?callback=Unpaid_Data"></script>
		<div class="shoppingcart_wrapper" id="ad_cpt_11850"><div><a href="http://a.dangdang.com/tjump.php?q=ddo84XQOf357bOs8tXGg5%2F%2F0oVoDImt3DFWsMqu7ZMSVsfUMeOQJueASNiMLjq%2FdrXMLCKnVfyKEahteAh1ih%2ByKYrKGzhvL20LVbDzObRambBA0YPpivy5hR5foQ4Rt%2BTB" target="_blank" rel="nofollow"><img src="http://img62.ddimg.cn/2017/1/11/2017011111344969879.jpg"></a></div></div>
<div class="logo_line">
    <div class="w960">
        <div class="shopping_procedure02 shopping_procedure "><span>我的购物车</span><span>填写订单</span><span class="current">完成订单</span></div>
        <div class="logo"><a href="#"><img src="/static/images/bz_logo_car.jpg" alt=""></a></div>
    </div>
</div>
<div class="checkout-wrap"><div class="indent_con">
	<div class="order-box orderEnd-box">
            <div class="orderEnd-box-top">
                <div class="topbar">
                </div>
                <h2>
                    <span id="spanOrderTip" class="text">感谢您提交订单，我们将及时为您处理！</span>
                    
                   
                </h2>
               
            </div>

            <div class="orderEnd-box-cont">
                <div id="NotPeerPayOrderList" class="pay-instead-order"> 
                
                
                </div>
                <div><h3 id="time_input"></h3><h3>秒后自动跳转</h3></div>
                {% if indent_num_obj %}
                    <div class="pay-normal" id="order_list"> <div class="item-order"><h3>订单：<a href="http://order.dangdang.com/orderdetails.aspx?orderid=34673930343" target="_blank"><span class="number">{{ indent_num_obj.num }}</span></a></h3><div class="cont minh-40"><table cellpadding="0" cellspacing="0">	 		<tbody><tr><td width="53"></td><td>		<span class="popup-Details spd">1件商品<i class="icon icon-details"></i><div class="popup-wrap popup-orderEnd-detail" style="right:-288px; top:12px;display:none;"><div class="popup-cont">		 			<p><span class="span-w230">活着（余华经典著作）</span><strong class="color-orange">x1</strong></p>				</div></div></span>			    	        <div class="popup-wrap popup-orderEnd-detail" style="right:-288px; top:12px;display:none;"><div class="popup-cont">			 				<p><span class="span-w230">活着（余华经典著作）</span><strong class="color-orange">x1</strong></p>			</div></div><span>送给</span><span class="popup-Details spd">郭雅雪<i class="icon icon-details"></i><div class="popup-wrap popup-orderEnd-detail" style="right:-288px; top:12px;display:none;"><div class="popup-cont"><p>中国 北京 北京市 海淀区 西二旗铭科苑小区十一号楼二单元601 100019</p><p>电话：15901551248</p></div></div></span><span>配送方为</span><span>百知网</span>   		</td></tr>							<tr class="hackie6"><td>&nbsp;</td></tr>					</tbody></table></div>					<div class="order-price"><p>支付金额：<span class="price-d">¥{{ indent_num_obj.price }}</span>        </p><p class="p-hdfk">货到付款</p></div>					<div class="itemtext"><span class="color-red">安全提醒：</span>当当平台及销售商不会以订单异常、系统升级等理由，通过任何方式发送给您退款链接。请您谨防<span class="color-red">钓鱼链接或诈骗电话</span>！</div></div></div>
                {% endif %}
                <div class="item-order item-order-payment" id="error_prompt" style="display:none;"> <!-- 需要隐藏，添加hide类即可 -->
                    <div class="tips-pay">
                        <strong>温馨提示：</strong>
                        <span>如果您有网上支付、银行转账的订单，请您在<strong class="color-red">24</strong>小时内支付 <a href="http://order.dangdang.com/myallorders" id="a_myorder">查看订单</a> </span><br>
                        <span style="padding-left:67px;">您还有 <strong class="color-red">1</strong> 张"待提交"订单 <a href="http://shopping.dangdang.com/shoppingcart/dispart_order.aspx" id="a_submitorder">继续提交</a></span>
                    </div>
                </div>
            </div>
        </div>
    
     
</div></div>

<div id="footer">
<div class="footer">
	<div class="footer_nav_box">
		<div class="footer_copyright"><span>Copyright (C) 当当网 2004-2014, All Rights Reserved</span><a href="http://www.hd315.gov.cn/beian/view.asp?bianhao=010202001051000098" target="_blank" class="footer_img" rel="nofollow"><img src="http://img4.dangdang.com/bottom/validate.gif"></a><span><a href="http://www.miibeian.gov.cn/" target="_blank" rel="nofollow">京ICP证041189号</a></span><span>出版物经营许可证&nbsp;新出发京批字第直0673号</span></div>
	</div>
</div>
</div>
    <div class="foot_tip_ad">广告</div>
    <style>
        .foot_tip_ad { width:40px; height:40px; font:12px/40px "simsun"; text-align:center; color:#fff; background-color:#474747; position:fixed; right:0; bottom:10px;_position:absolute; _bottom:auto;_top:expression(eval(document.documentElement.scrollTop+document.documentElement.clientHeight-this.offsetHeight-(parseInt(this.currentStyle.marginTop,10)||0)-(parseInt(this.currentStyle.marginBottom,10)||0)));}
    </style>


</body>
<script>
    var time_input=document.getElementById('time_input');
    var date = new Date();
    var now = 10;
    setInterval(function () {
{#        var now1 = date.getTime();#}
        now=now-1;
        time_input.innerHTML=now;
    },1000);
    setTimeout(function () {
        location.href="{% url 'mainapp:index' %}"
    },10000)
</script>
</html>